//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyProdsEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautyProdsEntities : DbContext
    {
        public BeautyProdsEntities()
            : base("name=BeautyProdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bottle> Bottles { get; set; }
        public virtual DbSet<BottleRequest> BottleRequests { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
